name: Greetings module pipeline
on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up go
        uses: actions/setup-go@v5

      - name: Install dependecies
        run: go mod tidy

      - name: Code quality
        run: go fmt && go vet

      - name: Building the app
        run: go build .
